arch: s390x
services:
- docker
script: 
  - docker build -t s390x-clefos-mono -f Dockerfile .
before_deploy:
    - docker tag  s390x-clefos-mono  "$DOCKER_USERNAME"/s390x-clefos-mono:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin  
deploy:
  provider: script
  script: 
     docker push "$DOCKER_USERNAME"/s390x-clefos-mono:latest
  on:
    branch: master  
notifications:
  slack: gbs-cai:8YOiAOuRbt0a2y5He5gkLfWb
    